// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4kBy3BPjXutyR3lb9DRcocg4B8YyeCtI',
    appId: '1:849612498144:web:affe7bb6a8d89576ec9c85',
    messagingSenderId: '849612498144',
    projectId: 'smart-budget-app-643f1',
    authDomain: 'smart-budget-app-643f1.firebaseapp.com',
    storageBucket: 'smart-budget-app-643f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdd6iUvba2-xjmm1wPKE1QVlKUehbOO_M',
    appId: '1:849612498144:android:86a6fc55e3ea5dc5ec9c85',
    messagingSenderId: '849612498144',
    projectId: 'smart-budget-app-643f1',
    storageBucket: 'smart-budget-app-643f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByk_Jb7ojp2mpUkkctKKmSQ1b82FykUoM',
    appId: '1:849612498144:ios:5df83891b2ae8096ec9c85',
    messagingSenderId: '849612498144',
    projectId: 'smart-budget-app-643f1',
    storageBucket: 'smart-budget-app-643f1.firebasestorage.app',
    iosBundleId: 'com.example.smartBudgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByk_Jb7ojp2mpUkkctKKmSQ1b82FykUoM',
    appId: '1:849612498144:ios:5df83891b2ae8096ec9c85',
    messagingSenderId: '849612498144',
    projectId: 'smart-budget-app-643f1',
    storageBucket: 'smart-budget-app-643f1.firebasestorage.app',
    iosBundleId: 'com.example.smartBudgetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4kBy3BPjXutyR3lb9DRcocg4B8YyeCtI',
    appId: '1:849612498144:web:6e2baaa95872d6e2ec9c85',
    messagingSenderId: '849612498144',
    projectId: 'smart-budget-app-643f1',
    authDomain: 'smart-budget-app-643f1.firebaseapp.com',
    storageBucket: 'smart-budget-app-643f1.firebasestorage.app',
  );
}
